stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE: "node:latest"

cache:
  paths:
    - node_modules/
    - .npm/

build:
  stage: build
  tags:
    - node
  image: $DOCKER_IMAGE
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build/

deploy:
  stage: deploy
  tags:
    - node
  image: docker:stable
  services:
    - name: docker:stable-dind
      alias: docker
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker info
    - docker build -t pm-dashboard ./build
    - docker stop pm-dashboard || true
    - docker rm pm-dashboard || true
    - docker run -d --name pm-dashboard -p 8090:3000 pm-dashboard